### ISSUE TITLE
Doesn't work on images 15MP or more anymore

### ISSUE THREAD

**Issue by thinkpad4** [bijij/ViewImage#131]
@bijij Just gives a data:image/jpeg;base64 then a tiny thumbnail size image

**Comment by needforsuv** [comment]
if you're on firefox
https://github.com/heubergen/viewimages
this still works

**Comment by bijij** [comment]
This seems to be fixed? or at least in my testing just now worked as expected.

**Comment by needforsuv** [comment]
#190
issue back as of redesign. (and related images or images using encrypted thumbnails don't work either - no button at all)

I think I know why though.

The way it worked before (related images and main panel) was that it had the full url BEFORE clicking (either in the main search or related search panel) but now with the redesign, only the main search page will have the full url once you click on an image.

And for related images, that full url disappears once you click in an image BECAUSE with the old google image search version, the BASE/SELECTED image result is ALWAYS shown as one of the results in the related images, BUT now clicking on a related images changes all the related contents and the 'desired' url panel no longer exists!


Google seems a bit picky with loading full sized images, maybe there is a way to 'force' it load them?

**Comment by needforsuv** [comment]
#190
issue back as of redesign. (and related images or images using encrypted thumbnails don't work either - no button at all)

I think I know why though.

The way it worked before (related images and main panel) was that it had the full url BEFORE clicking (either in the main search or related search panel) but now with the redesign, only the main search page will have the full url once you click on an image.

And for related images, that full url disappears once you click in an image BECAUSE with the old google image search version, the BASE/SELECTED image result is ALWAYS shown as one of the results in the related images, BUT now clicking on a related images changes all the related contents and the 'desired' url panel no longer exists!

Google seems a bit picky with loading full sized images, maybe there is a way to 'force' it load them?

(this is for the 'JUL19' version)

**Comment by wfaulk** [comment]
It looks like

```
document.getElementsByClassName("YcWSDf")[0].parentElement.getElementsByTagName("img")[0].parentElement.parentElement.href
```

will get you the href you need in https://github.com/bijij/ViewImage/blob/a59ce8baf0c164ede1bf91ab6d359886e8425b7c/js/content-script.js#L99
