### ISSUE TITLE
Selecting alt image options don't update view image link

### ISSUE THREAD

**Issue by asdgfd** [bijij/ViewImage#3]
When an image is selected/highlighted, there is often thumbnails toward the lower right side (below the buttons) for alternate image thumbnails (usually images that are similar). When selecting one of the alternate images thumbnails, the link to view image remains pointing to the originally selected image.

**Comment by saitanay** [comment]
This PR should fix this problem. 
https://github.com/bijij/ViewImage/pull/6

**Comment by danielhickman** [comment]
I don't think this is fixed after #6. `thumbnail` doesn't exist for the related images because they are not necessarily in the original search results. The current behavior is you get the following error when clicking on a related image and when you click back to the original in the related list, it finds the thumbnail as expected.

```
Uncaught TypeError: Cannot read property 'closest' of null
```

I think this should be reopened for evaluation.

**Comment by bijij** [comment]
From my testing, commit 480355034f4ceefb91a68e7961388a87b7dcb34f fixes this issue.
