### ISSUE TITLE
Not working in Firefox Quantum 58.0.2 or 59.0 (64-bit)

### ISSUE THREAD

**Issue by dle0105** [bijij/ViewImage#98]
Not sure what happened, but I can't get it to work in this browser. It loads up and I can change options, but there isn't a "View Image" button on any images.

**Comment by bijij** [comment]
I'll take a look in a few hours and see if I can replicate.

**Comment by marioferpa** [comment]
I have the same problem with Firefox 52.6.0 (64-bit). I'm using Debian 9.3 stretch so I'm stuck at that version.

**Comment by thrisp** [comment]
I get the same. 

This extension isn't working, also other scripts (i.e. greasemonkey) don't do anything for me.

**Comment by bijij** [comment]
Unable to replication Firefox Quantum v 58.0.2 so not 100% sure what the issue might be
![image](https://user-images.githubusercontent.com/8677174/36965000-017bddd8-20a4-11e8-8dde-39af230586a5.png)

**Comment by S0lstickan** [comment]
Same version of FF here. For me it works very wonky.
* Sometimes there just is no View Image at all.
* Sometimes there is a button, but I'm taken to the site instead of the image directly.
* Sometimes I'm taken to a low res image instead, basically a thumbnail or around 200px, even if the picture is 700px or 50000px or something.
* However, what I'm never getting anymore, is the actual intended result of getting directly to the source image in it's correct resolution.

**Comment by oraculus** [comment]
Is not working for my either. The extension installs fine but no button appears.

**Comment by pat-cw** [comment]
Firefox 58.0.2 not working 🤙

**Comment by ambroza** [comment]
Not working on Firefox 59.0 if you are logged into Google account.

If you logout from Google account or use incognito mode, "VIew image" button appears.

**Comment by dle0105** [comment]
So after tinkering around a bit (deleting chrome folder, disabling all other addons, etc.), I've discovered that it only works when I open a private browsing window. I wonder if there is maybe a setting somewhere in about:config that needs changed?

**Comment by krystian3w** [comment]
Try remove **cookies** and **cache**.

> `about:preferences#privacy`
>
> ![image](https://user-images.githubusercontent.com/35370833/37656285-e5331628-2c47-11e8-938b-eeef8d3c6ef7.png)
